# cat /usr/local/man/man1/test_script.1
." Process this file with
." groff -man -Tascii man_1_simple_shell.1
."
.TH simple_shell(1)

.Sh NAME
.B simple shell interpreter
- user interface to perform some task

.SH SYNOPSIS

.B uninteractive mode:
.RB echo
.RB """command -[OPTIONS] --[OPTIONS2]"""

.B interactive mode:
.RB command
.RB "-[OPTIONS] --[OPTIONS2]"

.SH DESCRIPTION
.B SIMPLE SHELL
This is a simple linux command line interpreter(shell), run simple commands such as ls,pwd... the shell takes in a string of command and
arguments, this shell searches for command available in paths available in PATH.

.RS
.nf
- Can
- list directories
- Run simple programs and system commands on user's path
.RE

.SH OBJECT
.TP
.B -^-a1|-arg1 <arg1_value>
Provide command. Must be on fIPATHfR to be able to run commands. the command could a simple linux command or program executable

.SH OPTIONS
.IP "fB--arg4fP <arg4_value>"
Shell Also takes in command arguments

.IP "fB-h|--helpfP"
Prints help


.SH EXAMPLES
.TP
.BI  echo " " 'ls " " -l " " /tmp' " " | " "./hsh
.TP
.PP
Run shell non-interactively by passing in commands from a string
.TP
.BI ($) " " ls " " -l " " /tmp
.TP
.PP
Run shell in interactive mode and passing in commands
.TP
.BI ($) " " /bin/ls " " -la
.TP
.PP
The full path to the executable can also be provided if not shell searches for it in PATH


.SH DIAGNOSTICS
.PP
The activity performed using this utility is logged in the file fB/var/log/simple_shellfR

.SH RETURN
.TP
.B
0
The Path handler returns 0 if command matches any file in PATH and appends the full path to it's executable

.TP
.B
-1 Else returns -1 meaning the command wasn't found and an error is printed however if it proceed to execute if it's an inbuilt command

.SH EXIT STATUS
.TP
.B
0
Success

.TP
.B
1
Fail

.SH COPYRIGHT
.PP
Copyright 2021 Simple Shell All rights reserved
https://github.com/AmidBidee/simple_shell

.SH CREDITS
.PP
This man page is created only for demonstration purpose by Aaron Ahmid Balogun

.TS
tab(@), left, box;
c | c
rB | r.
TEAM@Contributors
_
Name@Elijah Daniel, Aaron Balogun
.TE
.RE

.SH
.PP
simple_shell(1)
